name: On push

on:
  push:

jobs:
  on-push:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - uses: actions/setup-java@v4
        with:
          java-version: '21'
          distribution: 'temurin'

      - name: Test
        run: ./mill __.test

      - name: Lint
        run: ./mill __.checkFormatAll
